/* Agri-Link AI — Cassino buyers database (v0.1, desk research). See project README. */
const DB = {
  "meta": {
    "name": "Agri-Link AI — Cassino Buyers Database",
    "version": "0.1 (MVP prototype)",
    "built": "2026-07-17",
    "method": "Desk research from public sources (review platforms, business directories, official sites, local press). No field visits.",
    "disclaimer": "Business names, types and locations come from public listings. Fields 'needs', 'volume' and 'quality_focus' are INFERRED from cuisine type and reviews for prototype purposes — they must be verified by real outreach before commercial use.",
    "categories": ["verdure", "pomodori", "frutta", "legumi", "olio", "vino", "uova", "formaggi", "carne", "erbe", "castagne", "miele", "conserve"],
    "volume_bands_kg_week": { "low": "under 50", "medium": "50-200", "high": "over 200" }
  },
  "buyers": [
    { "id": "b01", "name": "Trattoria La Cantina", "type": "trattoria", "zone": "Cassino centro", "distance_km": 1, "needs": ["verdure", "pomodori", "legumi", "carne"], "volume": "medium", "quality_focus": ["tradizionale", "prezzo"], "notes": "Rotating weekly menu at accessible prices — flexible buyer for whatever is in season.", "source": "gastroranking.it", "confidence": "high" },
    { "id": "b02", "name": "La Brunella Arr'Osteria", "type": "osteria", "zone": "Cassino centro", "distance_km": 1, "needs": ["verdure", "pomodori", "carne", "olio"], "volume": "low", "quality_focus": ["tradizionale", "genuino"], "notes": "Small, genuine home-style cooking; reviewers praise carpacci and freshness.", "source": "gastroranking.it", "confidence": "high" },
    { "id": "b03", "name": "Kasa Falese", "type": "ristorante", "zone": "Cassino centro", "distance_km": 1, "needs": ["verdure", "legumi", "carne", "olio"], "volume": "medium", "quality_focus": ["tradizionale"], "notes": "Listed among top traditional-cuisine restaurants in Cassino.", "source": "thefork.it", "confidence": "medium" },
    { "id": "b04", "name": "La Locandiera", "type": "ristorante", "zone": "Cassino centro", "distance_km": 1, "needs": ["carne", "verdure", "legumi"], "volume": "medium", "quality_focus": ["tradizionale"], "notes": "Traditional dishes (pork shank praised); honest pricing.", "source": "gastroranking.it", "confidence": "high" },
    { "id": "b05", "name": "Locanda D'Amore", "type": "ristorante", "zone": "Cassino centro", "distance_km": 1, "needs": ["pomodori", "verdure", "erbe"], "volume": "medium", "quality_focus": ["tradizionale", "qualità"], "notes": "Family-run, called one of the best in town; polpette and seafood pasta.", "source": "gastroranking.it", "confidence": "high" },
    { "id": "b06", "name": "Hosteria Santé", "type": "ristorante", "zone": "Cassino centro", "distance_km": 1, "needs": ["erbe", "verdure", "olio"], "volume": "low", "quality_focus": ["alta_qualità", "creativo"], "notes": "Refined fish restaurant; small volumes but pays for excellent quality garnish produce and oil.", "source": "gastroranking.it", "confidence": "high" },
    { "id": "b07", "name": "Colle de Siena", "type": "ristorante", "zone": "Cassino", "distance_km": 2, "needs": ["verdure", "frutta", "olio"], "volume": "medium", "quality_focus": ["alta_qualità"], "notes": "Reviews highlight fresh, quality ingredients and balanced dishes.", "source": "gastroranking.it", "confidence": "high" },
    { "id": "b08", "name": "Regina Margherita Italia", "type": "ristorante", "zone": "Cassino centro", "distance_km": 1, "needs": ["pomodori", "verdure", "formaggi"], "volume": "medium", "quality_focus": ["qualità"], "notes": "TheFork rating 9/10; Italian classics.", "source": "sluurpy.it / thefork.it", "confidence": "medium" },
    { "id": "b09", "name": "Riva Seafood Restaurant", "type": "ristorante", "zone": "Cassino", "distance_km": 2, "needs": ["erbe", "verdure", "olio"], "volume": "low", "quality_focus": ["alta_qualità"], "notes": "Top-rated seafood (9.4 on TheFork); limited but premium produce needs.", "source": "thefork.it", "confidence": "medium" },
    { "id": "b10", "name": "Ristorante Evans dal 1960", "type": "ristorante", "zone": "Cassino", "distance_km": 2, "needs": ["verdure", "erbe", "olio"], "volume": "medium", "quality_focus": ["storico", "qualità"], "notes": "Historic restaurant (since 1960), fish focus, outdoor tables.", "source": "sluurpy.it", "confidence": "medium" },
    { "id": "b11", "name": "Ristorante Villa Grazia", "type": "ristorante_eventi", "zone": "Cassino", "distance_km": 3, "needs": ["verdure", "pomodori", "carne", "frutta"], "volume": "high", "quality_focus": ["eventi"], "notes": "Garden venue, banquets and ceremonies — demand spikes for events.", "source": "sluurpy.it", "confidence": "medium" },
    { "id": "b12", "name": "A Casa di Simonetta", "type": "trattoria", "zone": "Cassino", "distance_km": 2, "needs": ["verdure", "uova", "legumi"], "volume": "low", "quality_focus": ["casalingo"], "notes": "Home-style cooking with outdoor seating.", "source": "sluurpy.it", "confidence": "medium" },
    { "id": "b13", "name": "La Conchiglia Ristorante Pizzeria", "type": "ristorante_pizzeria", "zone": "Cassino", "distance_km": 2, "needs": ["pomodori", "verdure", "formaggi"], "volume": "medium", "quality_focus": ["famiglie"], "notes": "Dual restaurant-pizzeria; steady tomato and vegetable topping needs.", "source": "sluurpy.it", "confidence": "medium" },
    { "id": "b14", "name": "Antica Osteria Giallo Limone", "type": "osteria", "zone": "Cassino", "distance_km": 2, "needs": ["verdure", "erbe", "olio"], "volume": "low", "quality_focus": ["tradizionale"], "notes": "Osteria noted for fish dishes.", "source": "sluurpy.it", "confidence": "medium" },
    { "id": "b15", "name": "Il Mago degli Arrosti", "type": "rosticceria", "zone": "Cassino centro (Via G. Marconi 76)", "distance_km": 1, "needs": ["carne", "verdure", "olio"], "volume": "medium", "quality_focus": ["tradizionale"], "notes": "Roast meat specialist; side-dish vegetables and quality oil.", "source": "virgilio.it", "confidence": "high" },
    { "id": "b16", "name": "I Carnivori Steakhouse", "type": "steakhouse", "zone": "Cassino", "distance_km": 2, "needs": ["carne", "verdure"], "volume": "medium", "quality_focus": ["carne"], "notes": "Meat-focused; contorni vegetables needed year-round.", "source": "sluurpy.it", "confidence": "medium" },
    { "id": "b17", "name": "Konig", "type": "birreria_ristorante", "zone": "Cassino", "distance_km": 1, "needs": ["carne", "verdure", "pomodori"], "volume": "medium", "quality_focus": ["informale"], "notes": "Beer house with meat dishes; high-traffic casual venue.", "source": "sluurpy.it", "confidence": "medium" },
    { "id": "b18", "name": "IL Bettoliere", "type": "ristorante", "zone": "Cassino", "distance_km": 2, "needs": ["carne", "verdure", "pomodori", "formaggi"], "volume": "high", "quality_focus": ["famiglie", "abbondanza"], "notes": "Large family venue with parking; burgers and meat; generous portions = steady volumes.", "source": "gastroranking.it", "confidence": "high" },
    { "id": "b19", "name": "Ristorante Il Rubino", "type": "ristorante_eventi", "zone": "Cassino", "distance_km": 3, "needs": ["verdure", "carne", "frutta"], "volume": "high", "quality_focus": ["eventi", "matrimoni"], "notes": "Wedding/event location (New Year dinner for large groups) — big spot orders.", "source": "gastroranking.it", "confidence": "medium" },
    { "id": "b20", "name": "Casale San Germano", "type": "ristorante_eventi", "zone": "Cassino", "distance_km": 3, "needs": ["verdure", "frutta", "carne"], "volume": "high", "quality_focus": ["eventi", "estate"], "notes": "Buffet events venue, strong in summer — seasonal produce in quantity.", "source": "gastroranking.it", "confidence": "high" },
    { "id": "b21", "name": "Jami Sushi Experience", "type": "sushi", "zone": "Cassino centro", "distance_km": 1, "needs": ["verdure"], "volume": "low", "quality_focus": ["alta_qualità"], "notes": "Quality-first sushi; minimal local produce needs — example of a LOW-fit buyer.", "source": "gastroranking.it", "confidence": "high" },
    { "id": "b22", "name": "GianPà Pizzeria Napoletana", "type": "pizzeria", "zone": "Cassino", "distance_km": 1, "needs": ["pomodori", "verdure", "formaggi", "olio"], "volume": "high", "quality_focus": ["napoletana", "qualità"], "notes": "1350+ reviews; Neapolitan pizza — grilled vegetables and cherry tomatoes in season.", "source": "gastroranking.it", "confidence": "high" },
    { "id": "b23", "name": "Pizza e Babbà", "type": "pizzeria", "zone": "Cassino", "distance_km": 1, "needs": ["pomodori", "verdure", "olio"], "volume": "high", "quality_focus": ["qualità_ingredienti"], "notes": "Reviewers single out the marinara's delicious tomato — ingredient quality is their selling point.", "source": "gastroranking.it", "confidence": "high" },
    { "id": "b24", "name": "Edra Palace Hotel & Ristorante", "type": "hotel_ristorante", "zone": "Cassino", "distance_km": 1, "needs": ["frutta", "verdure", "uova", "miele", "conserve"], "volume": "high", "quality_focus": ["4_stelle", "colazioni", "eventi"], "notes": "4-star, 79 rooms, two banquet halls — daily breakfast fruit/eggs plus event catering.", "source": "edrapalacehotel.it", "confidence": "high" },
    { "id": "b25", "name": "Forum Palace Hotel & Spa", "type": "hotel_ristorante", "zone": "Cassino", "distance_km": 2, "needs": ["verdure", "frutta", "carne", "uova"], "volume": "high", "quality_focus": ["congressi", "eventi"], "notes": "Hotel + spa + congress venue with restaurant — institutional-scale kitchen.", "source": "meetinglocation.it", "confidence": "high" },
    { "id": "b26", "name": "Best Western Hotel Rocca", "type": "hotel_ristorante", "zone": "Cassino", "distance_km": 2, "needs": ["frutta", "uova", "miele", "verdure"], "volume": "medium", "quality_focus": ["4_stelle", "colazioni", "business"], "notes": "4-star business hotel — steady breakfast buffet demand.", "source": "booking.com", "confidence": "high" },
    { "id": "b27", "name": "Agriturismo Il Pioppeto", "type": "agriturismo", "zone": "Sant'Elia Fiumerapido", "distance_km": 6, "needs": ["verdure", "legumi", "olio", "formaggi"], "volume": "medium", "quality_focus": ["km0", "territorio", "vegetariano"], "notes": "Restaurant open to the public, typical territory cuisine, vegetarian/celiac menus — km0 is their identity.", "source": "agriturismo.it / paginegialle.it", "confidence": "high" },
    { "id": "b28", "name": "L'Azione Country House", "type": "agriturismo", "zone": "Sant'Elia Fiumerapido (Via della Bonifica 556)", "distance_km": 6, "needs": ["pomodori", "verdure", "carne"], "volume": "medium", "quality_focus": ["tradizionale"], "notes": "Country house with restaurant + pizzeria + rooms.", "source": "paginegialle.it", "confidence": "high" },
    { "id": "b29", "name": "Crete Gialle", "type": "agriturismo", "zone": "Cassino (campagna)", "distance_km": 4, "needs": ["frutta", "verdure"], "volume": "medium", "quality_focus": ["estate", "eventi"], "notes": "Pool, restaurant and bar — strong summer season.", "source": "bluepillow.it", "confidence": "medium" },
    { "id": "b30", "name": "Ristorante Alessio - Locanda Cicchini", "type": "agriturismo", "zone": "Cervaro area", "distance_km": 6, "needs": ["carne", "verdure", "olio"], "volume": "medium", "quality_focus": ["km0", "griglia"], "notes": "Advertises local products, grilled meat, homemade desserts.", "source": "agriturismo.it", "confidence": "medium" },
    { "id": "b31", "name": "Agriturismo La Grande Quercia", "type": "agriturismo", "zone": "Sant'Elia Fiumerapido area", "distance_km": 7, "needs": ["verdure", "olio", "legumi"], "volume": "low", "quality_focus": ["km0"], "notes": "Listed agriturismo in the S. Elia cluster; verify current activity.", "source": "virgilio.it", "confidence": "medium" },
    { "id": "b32", "name": "Agriturismo Colle Bralle", "type": "agriturismo", "zone": "Sant'Elia Fiumerapido area", "distance_km": 7, "needs": ["verdure", "legumi"], "volume": "low", "quality_focus": ["km0"], "notes": "Listed agriturismo near S. Elia; verify current activity.", "source": "virgilio.it", "confidence": "medium" },
    { "id": "b33", "name": "Agriturismo La Pesca", "type": "agriturismo", "zone": "Cassino surroundings", "distance_km": 5, "needs": ["frutta", "verdure"], "volume": "low", "quality_focus": ["km0"], "notes": "Listed in local agriturismo directories; verify current activity.", "source": "virgilio.it", "confidence": "medium" },
    { "id": "b34", "name": "Supermercati Angione", "type": "bottega_supermercato", "zone": "Cassino (Via C. Colombo 60)", "distance_km": 2, "needs": ["frutta", "verdure", "pomodori", "carne"], "volume": "high", "quality_focus": ["freschezza", "stagionale"], "notes": "Local supermarket with own butchery/deli, advertises seasonal fruit & veg — a recurring daily buyer.", "source": "supermercatiduea.it", "confidence": "high" },
    { "id": "b35", "name": "Di Vetta dal 1934", "type": "gastronomia", "zone": "Cassino (Via San Pasquale 93)", "distance_km": 1, "needs": ["conserve", "olio", "formaggi", "verdure", "legumi"], "volume": "medium", "quality_focus": ["storico", "tipico"], "notes": "Historic grocery-gastronomy (since 1934) — showcase for local specialty products.", "source": "paginegialle.it", "confidence": "high" },
    { "id": "b36", "name": "Pasticceria da Andrea 1972", "type": "pasticceria", "zone": "Cassino (Piazza G. Marconi 9)", "distance_km": 1, "needs": ["frutta", "uova", "miele", "castagne"], "volume": "medium", "quality_focus": ["artigianale"], "notes": "Pastry + gelato — seasonal fruit for gelato/tarts, eggs, chestnuts in autumn.", "source": "virgilio.it", "confidence": "high" }
  ],
  "channels": [
    { "id": "c01", "name": "Mercato settimanale di Cassino (ortofrutta)", "type": "mercato", "zone": "Piazza Nicholas Green", "distance_km": 1, "needs": ["frutta", "verdure", "pomodori", "legumi", "uova", "miele", "olio"], "volume": "high", "quality_focus": ["vendita_diretta"], "notes": "Saturday weekly market; produce stalls relocated to Piazza N. Green (2026). Requires a municipal stall/itinerant licence — a direct-sales channel, not a single buyer.", "source": "comune.cassino.fr.it / tg24.info", "confidence": "high" },
    { "id": "c02", "name": "Rete Campagna Amica (Coldiretti)", "type": "rete_km0", "zone": "Lazio network", "distance_km": 15, "needs": ["frutta", "verdure", "olio", "vino", "formaggi", "miele", "legumi"], "volume": "medium", "quality_focus": ["km0", "solo_produttori"], "notes": "National km0 farmers-market network. Membership gives access to dedicated markets and visibility — onboarding channel for small producers.", "source": "campagnamica.it", "confidence": "high" },
    { "id": "c03", "name": "Mense istituzionali (Università di Cassino, scuole)", "type": "istituzionale", "zone": "Cassino", "distance_km": 2, "needs": ["verdure", "frutta", "legumi", "pomodori"], "volume": "high", "quality_focus": ["gare_appalto", "continuità"], "notes": "Institutional canteens buy big, steady volumes but via public tenders — a medium-term target, flagged by the system as 'requires aggregation of multiple farmers'.", "source": "general — to verify", "confidence": "low" }
  ],
  "local_products_context": {
    "note": "Typical products of the Cassino / Valle dei Santi / Valle di Comino area, useful for demo scenarios and matching realism.",
    "products": ["Fagiolo Cannellino di Atina DOP", "Peperone di Pontecorvo DOP", "Fagiolo confettino di Terelle", "Castagne di Terelle", "Cabernet di Atina DOC", "Olio extravergine collinare del Cassinate"],
    "source": "provincia.fr.it / visitatina.com / fieradelbassolazio.it"
  }
};

/* Reference retail-equivalent price ranges (EUR/kg) per category — rough, editable
   assumptions used ONLY to estimate potential order value on the dashboard.
   NOT sourced live pricing data. Always shown to the user as an adjustable assumption. */
const PRICE_ASSUMPTIONS = {
  verdure: 1.8, pomodori: 1.6, frutta: 2.4, legumi: 5.5, olio: 9.0, vino: 6.0,
  uova: 3.2, formaggi: 12.0, carne: 14.0, erbe: 6.0, castagne: 4.0, miele: 9.5, conserve: 6.5
};

if (typeof module !== "undefined" && module.exports) { module.exports = { DB: DB, PRICE_ASSUMPTIONS: PRICE_ASSUMPTIONS }; }
